# docker-compose.yml
version: "3.9"
services:
  nginx:
    container_name: rmit_nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
  php:
    user: 1000:1000
    container_name: rmit_php
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html